# 설정 예시 파일
# 이 파일을 복사해서 application-local.yml로 만들고 실제 값들을 입력하세요

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/animal_shelter
    username: your_db_username
    password: your_db_password
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret: your-jwt-secret-key-here

openapi:
  shelter:
    url: "https://apis.data.go.kr/1543061/animalShelterSrvc_v2/shelterInfo_v2"
    service-key: "your-shelter-api-key-here"

app:
  upload-root: /path/to/your/upload/directory
