server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/animal_shelter
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  jackson:
    serialization:
      fail-on-empty-beans: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: DEBUG
  charset:
    console: UTF-8
    file: UTF-8

jwt:
  secret: ${JWT_SECRET:your-jwt-secret-key-here}

openapi:
  shelter:
    url: "https://apis.data.go.kr/1543061/animalShelterSrvc_v2/shelterInfo_v2"
    service-key: ${SHELTER_API_KEY:your-api-key-here}

ai:
  base-url: ${AI_BASE_URL:http://localhost:8000}  # 로컬 기본값

app:
  upload-root: ${UPLOAD_PATH:./uploads}
  
  cookie:
    name: refresh_token         # 쿠키 이름
    secure: false               # 로컬 http 이므로 false
    same-site: Lax              # localhost:5173 ↔ 8080은 same-site
    path: /                     # 전 경로에서 전송
    max-age-seconds: 1209600    # 14일 (60*60*24*14)
