apiVersion: v1
kind: Service
metadata:
  name: dogfinder-backend-service
  labels:
    app: dogfinder
    tier: backend
spec:
  type: LoadBalancer 
  ports:
  - port: 80 
    targetPort: 8080 
    protocol: TCP
  selector:
    app: dogfinder
    tier: backend 
