apiVersion: apps/v1
kind: Deployment
metadata:
  name: dogfinder-backend-deployment
  labels:
    app: dogfinder
    tier: backend
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: dogfinder
      tier: backend
  template:
    metadata:
      labels:
        app: dogfinder
        tier: backend
    spec:
      containers:
      - name: backend-container
        image: contest96.kr.ncr.ntruss.com/dogfinder-backend:$CODEBUILD_RESOLVED_SOURCE_VERSION 
        ports:
        - containerPort: 8080
        resources:
          limits: 
            memory: "1024Mi"
            cpu: "500m"
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
